apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoptal-auth-service
spec:
  template:
    spec:
      containers:
      - name: auth-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoptal-project-service
spec:
  template:
    spec:
      containers:
      - name: project-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoptal-ai-service
spec:
  template:
    spec:
      containers:
      - name: ai-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1500m"