apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: zoptal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: zoptal
data:
  redis.conf: |
    # Redis configuration
    save 900 1
    save 300 10
    save 60 10000
    
    # Memory management
    maxmemory 1gb
    maxmemory-policy allkeys-lru
    
    # Network
    tcp-keepalive 300
    timeout 0
    
    # Persistence
    appendonly yes
    appendfsync everysec
    
    # Security
    # requirepass will be set via environment variable
    
    # Performance
    tcp-backlog 511
    databases 16

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoptal-redis
  namespace: zoptal
  labels:
    app: redis
    component: cache
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        component: cache
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command:
        - redis-server
        - /etc/redis/redis.conf
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: REDIS_PASSWORD
              optional: true
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        - name: redis-storage
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: zoptal-redis
  namespace: zoptal
  labels:
    app: redis
    component: cache
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
  type: ClusterIP