import type { Metadata } from 'next';
import Link from 'next/link';
import { 
  HeartIcon,
  UserGroupIcon,
  ChartBarIcon,
  DevicePhoneMobileIcon,
  VideoCameraIcon,
  CalendarDaysIcon,
  BellIcon,
  TrophyIcon,
  CheckIcon,
  ArrowRightIcon,
  StarIcon,
  PlayIcon,
  ClockIcon,
  CurrencyDollarIcon,
  AcademicCapIcon,
  UsersIcon,
  BuildingOffice2Icon,
  DocumentChartBarIcon
} from '@heroicons/react/24/outline';
import FitnessWellnessHeroImage from '@/components/FitnessWellnessHeroImage';

export const metadata: Metadata = {
  title: 'Fitness & Wellness Platform | Virtual Training & Gym Management Solution | Zoptal',
  description: 'Launch your comprehensive fitness platform in 30-75 days. AI-powered workouts, virtual training, nutrition tracking, and gym management. Investment from $20K-55K.',
  keywords: [
    'fitness app development',
    'wellness platform',
    'virtual personal training',
    'gym management software',
    'workout tracking app',
    'nutrition logging platform',
    'fitness marketplace',
    'corporate wellness solution',
    'online fitness classes',
    'personal trainer app',
    'gym member management',
    'fitness tracking technology',
    'health and wellness app',
    'exercise platform development'
  ],
  openGraph: {
    title: 'Fitness & Wellness Platform | Zoptal',
    description: 'Launch your comprehensive fitness platform in 30-75 days.',
    images: ['/images/og-image.png'],
  },
};

const features = [
  {
    icon: HeartIcon,
    title: 'AI-Powered Workouts',
    description: 'Personalized exercise routines generated by AI based on fitness goals, experience level, and progress.'
  },
  {
    icon: VideoCameraIcon,
    title: 'Virtual Training Platform',
    description: 'Live and on-demand fitness classes with real-time interaction between trainers and clients.'
  },
  {
    icon: ChartBarIcon,
    title: 'Progress & Analytics',
    description: 'Comprehensive tracking of weight, measurements, strength gains, and performance metrics.'
  },
  {
    icon: BuildingOffice2Icon,
    title: 'Gym Management System',
    description: 'Complete fitness center operations including membership, scheduling, and equipment management.'
  }
];

const platformComponents = [
  {
    title: 'Fitness Enthusiast App',
    description: 'Comprehensive mobile app for individual users',
    features: [
      'AI-generated personalized workout plans',
      'Progress tracking & performance metrics',
      'Nutrition logging & meal planning',
      'Virtual fitness classes & challenges',
      'Social features & community support',
      'Wearable device integration',
      'Goal setting & achievement badges',
      'Exercise video library & tutorials'
    ]
  },
  {
    title: 'Fitness Professional Dashboard',
    description: 'Professional tools for trainers and coaches',
    features: [
      'Client management & scheduling',
      'Virtual training video tools',
      'Custom workout plan builder',
      'Business analytics & revenue tracking',
      'Marketing & client acquisition tools',
      'Certification & education tracking',
      'Payment processing & invoicing',
      'Performance assessment tools'
    ]
  },
  {
    title: 'Gym Owner Platform',
    description: 'Enterprise solution for fitness centers',
    features: [
      'Member management & billing',
      'Class scheduling & booking system',
      'Equipment monitoring & maintenance',
      'Staff management & payroll',
      'Financial reporting & forecasting',
      'Branded mobile app for members',
      'Multi-location support',
      'Integration with fitness equipment'
    ]
  }
];

const pricingPlans = [
  {
    name: 'Starter Package',
    price: '$20,000',
    timeline: '30-45 days',
    features: [
      'Basic fitness tracking app',
      'Workout & nutrition logging',
      'User profiles & progress tracking',
      'Simple exercise library',
      'Basic social features',
      'Standard UI/UX design',
      'iOS and Android apps',
      '3 months support included'
    ],
    ideal: 'Individual trainers and small fitness studios'
  },
  {
    name: 'Professional Package',
    price: '$35,000',
    timeline: '45-60 days',
    features: [
      'Virtual training platform',
      'Trainer/client management',
      'Live video class streaming',
      'Advanced analytics dashboard',
      'Payment & subscription system',
      'Custom branding options',
      'Wearable device integration',
      '6 months support included'
    ],
    ideal: 'Growing fitness businesses and training teams'
  },
  {
    name: 'Enterprise Package',
    price: '$55,000',
    timeline: '60-75 days',
    features: [
      'Complete fitness ecosystem',
      'Gym management features',
      'Multi-location support',
      'White-label customization',
      'AI-powered recommendations',
      'Advanced equipment integration',
      'Custom feature development',
      '12 months support included'
    ],
    ideal: 'Gym chains and enterprise wellness programs'
  }
];

const successMetrics = [
  { metric: '10,000+', label: 'Active Daily Users' },
  { metric: '85%', label: 'User Retention Rate' },
  { metric: '4.8/5', label: 'App Store Rating' },
  { metric: '3x', label: 'Revenue Growth' }
];

export default function FitnessWellnessPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white">
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-gradient-to-br from-green-600 via-green-500 to-emerald-600 text-white">
        <div className="absolute inset-0 bg-black/10"></div>
        <div className="relative mx-auto max-w-7xl px-6 py-24 sm:py-32 lg:px-8">
          <div className="grid gap-12 lg:grid-cols-2 lg:gap-8 items-center">
            <div>
              <div className="inline-flex items-center rounded-full bg-white/10 px-3 py-1 text-sm font-medium text-white backdrop-blur mb-6">
                <TrophyIcon className="mr-2 h-4 w-4" />
                Transform Fitness & Wellness
              </div>
              <h1 className="text-4xl font-bold tracking-tight sm:text-6xl mb-6">
                Launch Your Fitness Empire in 60 Days
              </h1>
              <p className="text-xl text-green-50 mb-8">
                Build the next generation fitness platform with AI-powered workouts, virtual training, and comprehensive wellness tracking. Connect fitness enthusiasts, trainers, and gyms in one powerful ecosystem.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 mb-8">
                <Link
                  href="/get-quote"
                  className="inline-flex items-center justify-center rounded-lg bg-white px-6 py-3 text-base font-semibold text-green-600 shadow-lg hover:bg-green-50 transition-all duration-200"
                >
                  Get Started
                  <ArrowRightIcon className="ml-2 h-5 w-5" />
                </Link>
                <Link
                  href="/contact"
                  className="inline-flex items-center justify-center rounded-lg bg-green-700 px-6 py-3 text-base font-semibold text-white hover:bg-green-800 transition-all duration-200"
                >
                  <PlayIcon className="mr-2 h-5 w-5" />
                  Watch Demo
                </Link>
              </div>
              <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
                {successMetrics.map((item, index) => (
                  <div key={index}>
                    <div className="text-2xl font-bold">{item.metric}</div>
                    <div className="text-sm text-green-100">{item.label}</div>
                  </div>
                ))}
              </div>
            </div>
            <div className="relative">
              <FitnessWellnessHeroImage className="w-full" />
            </div>
          </div>
        </div>
        <div className="absolute bottom-0 left-0 right-0 h-20 bg-gradient-to-t from-gray-50 to-transparent"></div>
      </section>

      {/* Platform Types */}
      <section className="py-20">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 sm:text-4xl mb-4">
              Choose Your Fitness Platform Type
            </h2>
            <p className="text-lg text-gray-600">
              Tailored solutions for every fitness business model
            </p>
          </div>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {[
              { title: 'Personal Fitness App', desc: 'Individual workout and health tracking', icon: HeartIcon },
              { title: 'Virtual Training Platform', desc: 'Online personal training and classes', icon: VideoCameraIcon },
              { title: 'Gym Management System', desc: 'Complete fitness center operations', icon: BuildingOffice2Icon },
              { title: 'Corporate Wellness', desc: 'Employee health and fitness programs', icon: UsersIcon },
              { title: 'Fitness Marketplace', desc: 'Connect trainers, nutritionists, and clients', icon: UserGroupIcon },
              { title: 'Specialized Training', desc: 'Sport-specific or rehabilitation focus', icon: AcademicCapIcon }
            ].map((type, index) => (
              <div key={index} className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm hover:shadow-md transition-shadow">
                <type.icon className="h-8 w-8 text-green-600 mb-3" />
                <h3 className="text-lg font-semibold text-gray-900 mb-2">{type.title}</h3>
                <p className="text-gray-600">{type.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Key Features */}
      <section className="py-20 bg-gray-50">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 sm:text-4xl mb-4">
              Powerful Features for Every User
            </h2>
            <p className="text-lg text-gray-600">
              Everything you need to build a successful fitness platform
            </p>
          </div>
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">
            {features.map((feature, index) => (
              <div key={index} className="text-center">
                <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-green-100">
                  <feature.icon className="h-8 w-8 text-green-600" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">{feature.title}</h3>
                <p className="text-gray-600">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Platform Components */}
      <section className="py-20">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 sm:text-4xl mb-4">
              Complete Fitness Ecosystem
            </h2>
            <p className="text-lg text-gray-600">
              Three powerful platforms working in perfect harmony
            </p>
          </div>
          <div className="grid gap-8 lg:grid-cols-3">
            {platformComponents.map((component, index) => (
              <div key={index} className="rounded-2xl border border-gray-200 bg-white overflow-hidden shadow-lg hover:shadow-xl transition-shadow">
                <div className="bg-gradient-to-r from-green-500 to-emerald-500 p-6">
                  <h3 className="text-xl font-bold text-white mb-2">{component.title}</h3>
                  <p className="text-green-50">{component.description}</p>
                </div>
                <div className="p-6">
                  <ul className="space-y-3">
                    {component.features.map((feature, idx) => (
                      <li key={idx} className="flex items-start">
                        <CheckIcon className="mr-3 h-5 w-5 text-green-500 flex-shrink-0 mt-0.5" />
                        <span className="text-gray-700">{feature}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section className="py-20 bg-gray-50">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900 sm:text-4xl mb-4">
              Investment Packages
            </h2>
            <p className="text-lg text-gray-600">
              Choose the perfect package for your fitness business
            </p>
          </div>
          <div className="grid gap-8 lg:grid-cols-3">
            {pricingPlans.map((plan, index) => (
              <div key={index} className={`rounded-2xl border ${index === 1 ? 'border-green-500 shadow-xl scale-105' : 'border-gray-200'} bg-white overflow-hidden`}>
                {index === 1 && (
                  <div className="bg-green-500 text-white text-center py-2 text-sm font-medium">
                    Most Popular
                  </div>
                )}
                <div className="p-8">
                  <h3 className="text-2xl font-bold text-gray-900 mb-2">{plan.name}</h3>
                  <div className="flex items-baseline mb-4">
                    <span className="text-4xl font-bold text-green-600">{plan.price}</span>
                    <span className="ml-2 text-gray-600">/ project</span>
                  </div>
                  <div className="flex items-center mb-6 text-gray-600">
                    <ClockIcon className="h-5 w-5 mr-2" />
                    <span>Launch in {plan.timeline}</span>
                  </div>
                  <ul className="space-y-3 mb-8">
                    {plan.features.map((feature, idx) => (
                      <li key={idx} className="flex items-start">
                        <CheckIcon className="mr-3 h-5 w-5 text-green-500 flex-shrink-0 mt-0.5" />
                        <span className="text-gray-700">{feature}</span>
                      </li>
                    ))}
                  </ul>
                  <p className="text-sm text-gray-600 mb-6">
                    <span className="font-semibold">Ideal for:</span> {plan.ideal}
                  </p>
                  <Link
                    href="/get-quote"
                    className={`block w-full text-center py-3 px-6 rounded-lg font-semibold transition-colors ${
                      index === 1 
                        ? 'bg-green-500 text-white hover:bg-green-600' 
                        : 'bg-gray-100 text-gray-900 hover:bg-gray-200'
                    }`}
                  >
                    Get Started
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Additional Features */}
      <section className="py-20">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="rounded-2xl bg-gradient-to-r from-green-500 to-emerald-500 p-12 text-white">
            <div className="grid gap-8 lg:grid-cols-2">
              <div>
                <h2 className="text-3xl font-bold mb-6">Advanced Technology Stack</h2>
                <ul className="space-y-3">
                  {[
                    'AI-powered workout recommendations',
                    'Real-time video streaming infrastructure',
                    'Cloud-based data synchronization',
                    'Machine learning for progress prediction',
                    'Biometric data analysis',
                    'Automated nutrition planning'
                  ].map((item, index) => (
                    <li key={index} className="flex items-center">
                      <CheckIcon className="mr-3 h-5 w-5" />
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h2 className="text-3xl font-bold mb-6">Integration Capabilities</h2>
                <ul className="space-y-3">
                  {[
                    'Apple Health & Google Fit',
                    'Fitbit, Garmin, and other wearables',
                    'Stripe & PayPal payment gateways',
                    'Zoom & WebRTC for video sessions',
                    'Social media platforms',
                    'Email marketing tools'
                  ].map((item, index) => (
                    <li key={index} className="flex items-center">
                      <CheckIcon className="mr-3 h-5 w-5" />
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-br from-green-600 to-emerald-600 text-white">
        <div className="mx-auto max-w-7xl px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-bold sm:text-4xl mb-6">
            Ready to Transform Fitness & Wellness?
          </h2>
          <p className="text-xl text-green-50 mb-8 max-w-3xl mx-auto">
            Join thousands of fitness professionals who have launched successful platforms with Zoptal. 
            Your complete fitness solution is just 60 days away.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/get-quote"
              className="inline-flex items-center justify-center rounded-lg bg-white px-8 py-4 text-lg font-semibold text-green-600 shadow-lg hover:bg-green-50 transition-all duration-200"
            >
              Start Your Fitness Platform
              <ArrowRightIcon className="ml-2 h-5 w-5" />
            </Link>
            <Link
              href="/contact"
              className="inline-flex items-center justify-center rounded-lg border-2 border-white px-8 py-4 text-lg font-semibold text-white hover:bg-white hover:text-green-600 transition-all duration-200"
            >
              <CalendarDaysIcon className="mr-2 h-5 w-5" />
              Schedule Consultation
            </Link>
          </div>
          <div className="mt-12 grid grid-cols-2 gap-8 md:grid-cols-4">
            {[
              { label: 'Platforms Launched', value: '500+' },
              { label: 'Active Users', value: '2M+' },
              { label: 'Countries', value: '45+' },
              { label: 'Client Satisfaction', value: '98%' }
            ].map((stat, index) => (
              <div key={index}>
                <div className="text-3xl font-bold">{stat.value}</div>
                <div className="text-green-100">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}