apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoptal-web-main
  namespace: zoptal
  labels:
    app: web-main
    component: frontend
    service: website
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web-main
  template:
    metadata:
      labels:
        app: web-main
        component: frontend
        service: website
    spec:
      containers:
      - name: web-main
        image: zoptal/web-main:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: zoptal-config
              key: NODE_ENV
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: zoptal-frontend-config
              key: NEXT_PUBLIC_AUTH_SERVICE_URL
        - name: NEXT_PUBLIC_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: zoptal-frontend-config
              key: NEXT_PUBLIC_AUTH_SERVICE_URL
        - name: NEXT_PUBLIC_SITE_URL
          valueFrom:
            configMapKeyRef:
              name: zoptal-frontend-config
              key: NEXT_PUBLIC_SITE_URL
        - name: NEXT_TELEMETRY_DISABLED
          valueFrom:
            configMapKeyRef:
              name: zoptal-frontend-config
              key: NEXT_TELEMETRY_DISABLED
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30

---
apiVersion: v1
kind: Service
metadata:
  name: zoptal-web-main
  namespace: zoptal
  labels:
    app: web-main
    component: frontend
    service: website
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: web-main
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zoptal-web-main-hpa
  namespace: zoptal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zoptal-web-main
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zoptal-web-main-pdb
  namespace: zoptal
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: web-main