# Istio Service Mesh Configuration for AI Service

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ai-service
  namespace: zoptal-production
spec:
  hosts:
  - ai-service
  - ai.zoptal.com
  gateways:
  - zoptal-gateway
  - mesh
  http:
  - match:
    - uri:
        prefix: /api/ai
    route:
    - destination:
        host: ai-service
        port:
          number: 3003
    timeout: 300s
    retries:
      attempts: 2
      perTryTimeout: 150s
      retryOn: 5xx,gateway-error,connect-failure,refused-stream
    fault:
      delay:
        percentage:
          value: 0.05
        fixedDelay: 2s
  - match:
    - uri:
        prefix: /health
    route:
    - destination:
        host: ai-service
        port:
          number: 3003
    timeout: 5s

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ai-service
  namespace: zoptal-production
spec:
  host: ai-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 50
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 5
        maxRetries: 2
        consecutiveGatewayErrors: 3
        interval: 60s
        baseEjectionTime: 60s
        maxEjectionPercent: 30
    circuitBreaker:
      consecutiveGatewayErrors: 3
      consecutive5xxErrors: 3
      interval: 60s
      baseEjectionTime: 60s
      maxEjectionPercent: 30
    outlierDetection:
      consecutiveGatewayErrors: 3
      consecutive5xxErrors: 3
      interval: 60s
      baseEjectionTime: 60s
      maxEjectionPercent: 30
      minHealthPercent: 70
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: canary
    labels:
      track: canary
  - name: stable
    labels:
      track: stable

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: ai-service
  namespace: zoptal-production
spec:
  selector:
    matchLabels:
      app: ai-service
  mtls:
    mode: STRICT

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ai-service
  namespace: zoptal-production
spec:
  selector:
    matchLabels:
      app: ai-service
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/zoptal-production/sa/auth-service"]
    - source:
        principals: ["cluster.local/ns/zoptal-production/sa/project-service"]
    - source:
        principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/health", "/ready", "/metrics"]
  - to:
    - operation:
        methods: ["POST"]
        paths: ["/api/ai/generate", "/api/ai/chat", "/api/ai/analyze"]
    when:
    - key: request.auth.claims[aud]
      values: ["zoptal-api"]
    - key: request.auth.claims[plan]
      values: ["pro", "enterprise"]

---
# AI service specific rate limiting - more restrictive
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ai-service-ratelimit
  namespace: zoptal-production
spec:
  workloadSelector:
    labels:
      app: ai-service
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: ai_service_rate_limiter
            token_bucket:
              max_tokens: 20
              tokens_per_fill: 5
              fill_interval: 60s
            filter_enabled:
              runtime_key: local_rate_limit_enabled
              default_value:
                numerator: 100
                denominator: HUNDRED
            filter_enforced:
              runtime_key: local_rate_limit_enforced
              default_value:
                numerator: 100
                denominator: HUNDRED

---
# External service entries for AI providers
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: ai-external-services
  namespace: zoptal-production
spec:
  hosts:
  - api.openai.com
  - api.anthropic.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS

---
# Destination rules for external AI services
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ai-external-services
  namespace: zoptal-production
spec:
  host: api.openai.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: api.openai.com
    connectionPool:
      tcp:
        maxConnections: 10
        connectTimeout: 30s
      http:
        http1MaxPendingRequests: 5
        maxRequestsPerConnection: 1
        maxRetries: 2
        consecutiveGatewayErrors: 3
        interval: 30s
        baseEjectionTime: 30s

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: anthropic-external-services
  namespace: zoptal-production
spec:
  host: api.anthropic.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: api.anthropic.com
    connectionPool:
      tcp:
        maxConnections: 10
        connectTimeout: 30s
      http:
        http1MaxPendingRequests: 5
        maxRequestsPerConnection: 1
        maxRetries: 2
        consecutiveGatewayErrors: 3
        interval: 30s
        baseEjectionTime: 30s

---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: ai-service
  namespace: zoptal-production
spec:
  selector:
    matchLabels:
      app: ai-service
  metrics:
  - providers:
    - name: prometheus
  - overrides:
    - match:
        metric: requests_total
      tagOverrides:
        request_protocol:
          value: "http"
        service_name:
          value: "ai-service"
        ai_provider:
          operation: UPSERT
          value: "{{.request.headers['x-ai-provider'] | default \"unknown\"}}"
  accessLogging:
  - providers:
    - name: otel
  tracing:
  - providers:
    - name: jaeger