# Istio Service Mesh Configuration for Billing Service

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: billing-service
  namespace: zoptal-production
spec:
  hosts:
  - billing-service
  - billing.zoptal.com
  gateways:
  - zoptal-gateway
  - mesh
  http:
  - match:
    - uri:
        prefix: /api/billing
    route:
    - destination:
        host: billing-service
        port:
          number: 3005
    timeout: 60s
    retries:
      attempts: 2
      perTryTimeout: 30s
      retryOn: 5xx,gateway-error,connect-failure,refused-stream
    fault:
      delay:
        percentage:
          value: 0.05
        fixedDelay: 1s
  - match:
    - uri:
        prefix: /api/webhooks/stripe
    route:
    - destination:
        host: billing-service
        port:
          number: 3005
    timeout: 30s
    retries:
      attempts: 1
      perTryTimeout: 15s
      retryOn: 5xx,gateway-error
  - match:
    - uri:
        prefix: /health
    route:
    - destination:
        host: billing-service
        port:
          number: 3005
    timeout: 5s

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: billing-service
  namespace: zoptal-production
spec:
  host: billing-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 50
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 10
        maxRetries: 2
        consecutiveGatewayErrors: 3
        interval: 30s
        baseEjectionTime: 30s
        maxEjectionPercent: 30
    circuitBreaker:
      consecutiveGatewayErrors: 3
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 30
    outlierDetection:
      consecutiveGatewayErrors: 3
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 30
      minHealthPercent: 70
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: canary
    labels:
      track: canary
  - name: stable
    labels:
      track: stable

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: billing-service
  namespace: zoptal-production
spec:
  selector:
    matchLabels:
      app: billing-service
  mtls:
    mode: STRICT

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: billing-service
  namespace: zoptal-production
spec:
  selector:
    matchLabels:
      app: billing-service
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/zoptal-production/sa/auth-service"]
    - source:
        principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/health", "/ready", "/metrics"]
  - to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
        paths: ["/api/billing/*"]
    when:
    - key: request.auth.claims[aud]
      values: ["zoptal-api"]
  # Allow Stripe webhooks
  - to:
    - operation:
        methods: ["POST"]
        paths: ["/api/webhooks/stripe"]
    when:
    - key: request.headers[stripe-signature]
      values: ["*"]

---
# External service entry for Stripe
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: stripe-external-service
  namespace: zoptal-production
spec:
  hosts:
  - api.stripe.com
  - hooks.stripe.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS

---
# Destination rule for Stripe API
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: stripe-external-service
  namespace: zoptal-production
spec:
  host: api.stripe.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: api.stripe.com
    connectionPool:
      tcp:
        maxConnections: 20
        connectTimeout: 30s
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 5
        maxRetries: 2
        consecutiveGatewayErrors: 3
        interval: 30s
        baseEjectionTime: 30s

---
# Rate limiting for billing operations
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: billing-service-ratelimit
  namespace: zoptal-production
spec:
  workloadSelector:
    labels:
      app: billing-service
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: billing_service_rate_limiter
            token_bucket:
              max_tokens: 50
              tokens_per_fill: 10
              fill_interval: 60s
            filter_enabled:
              runtime_key: local_rate_limit_enabled
              default_value:
                numerator: 100
                denominator: HUNDRED
            filter_enforced:
              runtime_key: local_rate_limit_enforced
              default_value:
                numerator: 100
                denominator: HUNDRED

---
# Webhook rate limiting (more permissive for Stripe)
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: billing-webhook-ratelimit
  namespace: zoptal-production
spec:
  workloadSelector:
    labels:
      app: billing-service
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        vhost:
          route:
            match:
              prefix: "/api/webhooks/stripe"
    patch:
      operation: MERGE
      value:
        typed_per_filter_config:
          envoy.filters.http.local_ratelimit:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: stripe_webhook_rate_limiter
              token_bucket:
                max_tokens: 1000
                tokens_per_fill: 100
                fill_interval: 60s

---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: billing-service
  namespace: zoptal-production
spec:
  selector:
    matchLabels:
      app: billing-service
  metrics:
  - providers:
    - name: prometheus
  - overrides:
    - match:
        metric: requests_total
      tagOverrides:
        request_protocol:
          value: "http"
        service_name:
          value: "billing-service"
        payment_provider:
          operation: UPSERT
          value: "{{.request.headers['x-payment-provider'] | default \"stripe\"}}"
  accessLogging:
  - providers:
    - name: otel
  tracing:
  - providers:
    - name: jaeger