apiVersion: v1
kind: Secret
metadata:
  name: zoptal-secrets
  namespace: zoptal
type: Opaque
stringData:
  # Database Credentials
  DATABASE_URL: "postgresql://postgres:CHANGE_ME@zoptal-postgres:5432/zoptal"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "CHANGE_ME"
  
  # Redis Configuration
  REDIS_URL: "redis://zoptal-redis:6379"
  REDIS_PASSWORD: ""
  
  # ClickHouse Credentials
  CLICKHOUSE_URL: "http://zoptal-clickhouse:8123"
  CLICKHOUSE_PASSWORD: "CHANGE_ME"
  
  # JWT Secrets
  JWT_SECRET: "CHANGE_ME_TO_SECURE_RANDOM_STRING"
  JWT_REFRESH_SECRET: "CHANGE_ME_TO_SECURE_RANDOM_STRING"
  
  # Email Service Keys
  SENDGRID_API_KEY: "CHANGE_ME"
  SMTP_HOST: "smtp.sendgrid.net"
  SMTP_USER: "apikey"
  SMTP_PASS: "CHANGE_ME"
  
  # SMS Service Keys
  TWILIO_ACCOUNT_SID: "CHANGE_ME"
  TWILIO_AUTH_TOKEN: "CHANGE_ME"
  TWILIO_PHONE_NUMBER: "CHANGE_ME"
  
  # OAuth Credentials
  GOOGLE_CLIENT_ID: "CHANGE_ME"
  GOOGLE_CLIENT_SECRET: "CHANGE_ME"
  GITHUB_CLIENT_ID: "CHANGE_ME"
  GITHUB_CLIENT_SECRET: "CHANGE_ME"
  
  # AI Service Keys
  OPENAI_API_KEY: "CHANGE_ME"
  ANTHROPIC_API_KEY: "CHANGE_ME"
  GOOGLE_AI_API_KEY: "CHANGE_ME"
  AZURE_OPENAI_ENDPOINT: "CHANGE_ME"
  AZURE_OPENAI_API_KEY: "CHANGE_ME"
  
  # Stripe Keys
  STRIPE_SECRET_KEY: "CHANGE_ME"
  STRIPE_PUBLISHABLE_KEY: "CHANGE_ME"
  STRIPE_WEBHOOK_SECRET: "CHANGE_ME"
  STRIPE_PRICE_API_REQUESTS: "CHANGE_ME"
  STRIPE_PRICE_CODE_GENERATIONS: "CHANGE_ME"
  
  # AWS Credentials
  AWS_ACCESS_KEY_ID: "CHANGE_ME"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME"
  AWS_S3_BUCKET: "zoptal-storage"
  
  # GitHub Integration
  GITHUB_APP_ID: "CHANGE_ME"
  GITHUB_PRIVATE_KEY: "CHANGE_ME"
  GITLAB_TOKEN: "CHANGE_ME"
  
  # Push Notification Keys
  VAPID_PUBLIC_KEY: "CHANGE_ME"
  VAPID_PRIVATE_KEY: "CHANGE_ME"

---
# Template for external secrets (use with External Secrets Operator)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: zoptal
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zoptal-external-secrets
  namespace: zoptal
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: zoptal-production-secrets
    creationPolicy: Owner
  data:
  - secretKey: DATABASE_PASSWORD
    remoteRef:
      key: zoptal/database
      property: password
  - secretKey: JWT_SECRET
    remoteRef:
      key: zoptal/jwt
      property: secret
  - secretKey: STRIPE_SECRET_KEY
    remoteRef:
      key: zoptal/stripe
      property: secret_key
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: zoptal/openai
      property: api_key