apiVersion: v1
kind: Namespace
metadata:
  name: zoptal-production
  labels:
    name: zoptal-production
    environment: production
    app.kubernetes.io/name: zoptal
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: zoptal-platform
    app.kubernetes.io/managed-by: kubernetes
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: zoptal-production-quota
  namespace: zoptal-production
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    pods: "50"
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: zoptal-production-limits
  namespace: zoptal-production
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "10m"
      memory: "64Mi"
    type: Container