apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cache-config
  namespace: zoptal-production
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log notice;
    pid /var/run/nginx.pid;
    
    # Optimize worker connections
    events {
        worker_connections 4096;
        use epoll;
        multi_accept on;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        # Logging format
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for" '
                        'rt=$request_time uct="$upstream_connect_time" '
                        'uht="$upstream_header_time" urt="$upstream_response_time"';
        
        access_log /var/log/nginx/access.log main;
        
        # Performance optimizations
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        keepalive_requests 1000;
        types_hash_max_size 2048;
        server_tokens off;
        
        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types
            text/plain
            text/css
            text/xml
            text/javascript
            application/json
            application/javascript
            application/xml+rss
            application/atom+xml
            image/svg+xml;
        
        # Brotli compression (if module available)
        brotli on;
        brotli_comp_level 6;
        brotli_types
            text/plain
            text/css
            application/json
            application/javascript
            text/xml
            application/xml
            application/xml+rss
            text/javascript;
        
        # Cache zones
        proxy_cache_path /var/cache/nginx/static levels=1:2 keys_zone=static_cache:100m max_size=10g inactive=7d use_temp_path=off;
        proxy_cache_path /var/cache/nginx/api levels=1:2 keys_zone=api_cache:50m max_size=1g inactive=1h use_temp_path=off;
        proxy_cache_path /var/cache/nginx/images levels=1:2 keys_zone=image_cache:100m max_size=5g inactive=30d use_temp_path=off;
        
        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
        limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=5r/s;
        limit_req_zone $binary_remote_addr zone=upload_limit:10m rate=2r/s;
        
        # Connection limiting
        limit_conn_zone $binary_remote_addr zone=conn_limit_per_ip:10m;
        limit_conn_zone $server_name zone=conn_limit_per_server:10m;
        
        # Upstream definitions
        upstream auth_service {
            least_conn;
            server auth-service:3001 max_fails=3 fail_timeout=30s;
            server auth-service:3001 max_fails=3 fail_timeout=30s;
            keepalive 32;
        }
        
        upstream project_service {
            least_conn;
            server project-service:3002 max_fails=3 fail_timeout=30s;
            server project-service:3002 max_fails=3 fail_timeout=30s;
            keepalive 32;
        }
        
        upstream ai_service {
            least_conn;
            server ai-service:3003 max_fails=3 fail_timeout=30s;
            server ai-service:3003 max_fails=3 fail_timeout=30s;
            keepalive 32;
        }
        
        upstream billing_service {
            least_conn;
            server billing-service:3004 max_fails=3 fail_timeout=30s;
            server billing-service:3004 max_fails=3 fail_timeout=30s;
            keepalive 32;
        }
        
        upstream notification_service {
            least_conn;
            server notification-service:3005 max_fails=3 fail_timeout=30s;
            server notification-service:3005 max_fails=3 fail_timeout=30s;
            keepalive 32;
        }

        # Main server block
        server {
            listen 80;
            server_name api.zoptal.com;
            
            # Security headers
            add_header X-Frame-Options DENY always;
            add_header X-Content-Type-Options nosniff always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header Referrer-Policy "strict-origin-when-cross-origin" always;
            add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;" always;
            
            # Connection limits
            limit_conn conn_limit_per_ip 20;
            limit_conn conn_limit_per_server 1000;
            
            # Health check endpoint
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
            
            # Static assets with aggressive caching
            location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$ {
                proxy_cache static_cache;
                proxy_cache_valid 200 7d;
                proxy_cache_valid 404 1m;
                proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
                proxy_cache_revalidate on;
                proxy_cache_lock on;

                expires 7d;
                add_header Cache-Control "public, immutable";
                add_header X-Cache-Status $upstream_cache_status;

                proxy_pass http://web_main;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            # API routes with rate limiting and caching
            location /api/auth {
                limit_req zone=auth_limit burst=20 nodelay;
                
                # Short cache for non-sensitive auth endpoints
                proxy_cache api_cache;
                proxy_cache_valid 200 5m;
                proxy_cache_valid 401 403 1m;
                proxy_cache_bypass $http_pragma $http_authorization;
                proxy_no_cache $http_pragma $http_authorization;
                
                proxy_pass http://auth_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # Timeouts
                proxy_connect_timeout 5s;
                proxy_send_timeout 10s;
                proxy_read_timeout 10s;
            }
            
            location /api/projects {
                limit_req zone=api_limit burst=50 nodelay;
                
                proxy_cache api_cache;
                proxy_cache_valid 200 10m;
                proxy_cache_valid 404 1m;
                proxy_cache_methods GET HEAD;
                proxy_cache_bypass $http_cache_control;
                proxy_cache_key "$scheme$request_method$host$request_uri";
                
                proxy_pass http://project_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                proxy_connect_timeout 5s;
                proxy_send_timeout 30s;
                proxy_read_timeout 30s;
            }
            
            location /api/ai {
                limit_req zone=api_limit burst=30 nodelay;
                
                # No caching for AI responses (dynamic content)
                proxy_cache off;
                
                proxy_pass http://ai_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # Longer timeouts for AI processing
                proxy_connect_timeout 10s;
                proxy_send_timeout 120s;
                proxy_read_timeout 120s;
                
                # WebSocket support for streaming
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }
            
            location /api/billing {
                limit_req zone=api_limit burst=20 nodelay;
                
                # Short cache for billing info
                proxy_cache api_cache;
                proxy_cache_valid 200 5m;
                proxy_cache_bypass $http_pragma $http_authorization;
                proxy_no_cache $http_pragma $http_authorization;
                
                proxy_pass http://billing_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                proxy_connect_timeout 5s;
                proxy_send_timeout 15s;
                proxy_read_timeout 15s;
            }
            
            location /api/notifications {
                limit_req zone=api_limit burst=30 nodelay;
                
                proxy_cache api_cache;
                proxy_cache_valid 200 2m;
                proxy_cache_valid 404 30s;
                
                proxy_pass http://notification_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                proxy_connect_timeout 5s;
                proxy_send_timeout 10s;
                proxy_read_timeout 10s;
            }
            
            # File uploads with special handling
            location /api/upload {
                limit_req zone=upload_limit burst=5 nodelay;
                
                # Disable caching for uploads
                proxy_cache off;
                
                # Increase upload limits
                client_max_body_size 100M;
                client_body_timeout 60s;
                proxy_request_buffering off;
                
                proxy_pass http://project_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                proxy_connect_timeout 10s;
                proxy_send_timeout 300s;
                proxy_read_timeout 300s;
            }
            
            # Image optimization and caching
            location /images/ {
                proxy_cache image_cache;
                proxy_cache_valid 200 30d;
                proxy_cache_valid 404 1h;
                proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
                
                expires 30d;
                add_header Cache-Control "public, immutable";
                add_header X-Cache-Status $upstream_cache_status;
                
                # Image optimization headers
                add_header Vary Accept;
                
                proxy_pass http://project_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            # Default location for web-main app
            location / {
                proxy_cache static_cache;
                proxy_cache_valid 200 1h;
                proxy_cache_valid 404 1m;
                proxy_cache_bypass $http_pragma;
                proxy_cache_revalidate on;

                proxy_pass http://web_main;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                proxy_connect_timeout 5s;
                proxy_send_timeout 10s;
                proxy_read_timeout 10s;
            }
        }
        
        # Cache purging endpoint (for authorized users only)
        server {
            listen 8080;
            server_name localhost;
            
            allow 10.0.0.0/8;
            allow 172.16.0.0/12;
            allow 192.168.0.0/16;
            deny all;
            
            location /purge {
                proxy_cache_purge static_cache $scheme$request_method$host$request_uri;
                return 200 "Purged\n";
            }
            
            location /purge-api {
                proxy_cache_purge api_cache $scheme$request_method$host$request_uri;
                return 200 "Purged\n";
            }
            
            location /status {
                stub_status on;
                access_log off;
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cache
  namespace: zoptal-production
  labels:
    app: nginx-cache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-cache
  template:
    metadata:
      labels:
        app: nginx-cache
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8080
          name: admin
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: cache-volume
          mountPath: /var/cache/nginx
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-cache-config
      - name: cache-volume
        emptyDir:
          sizeLimit: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cache-service
  namespace: zoptal-production
  labels:
    app: nginx-cache
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 8080
    targetPort: 8080
    name: admin
  selector:
    app: nginx-cache

---
# HPA for nginx cache
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-cache-hpa
  namespace: zoptal-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-cache
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60