apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoptal-ai-service
  namespace: zoptal
  labels:
    app: ai-service
    component: backend
    service: ai
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
        component: backend
        service: ai
    spec:
      containers:
      - name: ai-service
        image: zoptal/ai-service:latest
        ports:
        - containerPort: 4003
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: zoptal-config
              key: NODE_ENV
        - name: PORT
          value: "4003"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: REDIS_URL
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: zoptal-config
              key: AUTH_SERVICE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: JWT_SECRET
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: ANTHROPIC_API_KEY
        - name: GOOGLE_AI_API_KEY
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: GOOGLE_AI_API_KEY
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: AZURE_OPENAI_ENDPOINT
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: AZURE_OPENAI_API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4003
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4003
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 4003
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 30
      initContainers:
      - name: wait-for-auth-service
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          until curl -f http://zoptal-auth-service:4001/health; do
            echo "Waiting for Auth Service..."
            sleep 5
          done

---
apiVersion: v1
kind: Service
metadata:
  name: zoptal-ai-service
  namespace: zoptal
  labels:
    app: ai-service
    component: backend
    service: ai
spec:
  ports:
  - port: 4003
    targetPort: 4003
    protocol: TCP
    name: http
  selector:
    app: ai-service
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zoptal-ai-service-hpa
  namespace: zoptal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zoptal-ai-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zoptal-ai-service-pdb
  namespace: zoptal
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ai-service