apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoptal-notification-service
  namespace: zoptal
  labels:
    app: notification-service
    component: backend
    service: notification
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        component: backend
        service: notification
    spec:
      containers:
      - name: notification-service
        image: zoptal/notification-service:latest
        ports:
        - containerPort: 4005
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: zoptal-config
              key: NODE_ENV
        - name: PORT
          value: "4005"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: REDIS_URL
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: zoptal-config
              key: AUTH_SERVICE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: JWT_SECRET
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: SENDGRID_API_KEY
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: zoptal-config
              key: SMTP_PORT
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: SMTP_USER
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: SMTP_PASS
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: TWILIO_ACCOUNT_SID
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: TWILIO_AUTH_TOKEN
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: TWILIO_PHONE_NUMBER
        - name: VAPID_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: VAPID_PUBLIC_KEY
        - name: VAPID_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: VAPID_PRIVATE_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4005
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4005
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      initContainers:
      - name: wait-for-auth-service
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          until curl -f http://zoptal-auth-service:4001/health; do
            echo "Waiting for Auth Service..."
            sleep 5
          done

---
apiVersion: v1
kind: Service
metadata:
  name: zoptal-notification-service
  namespace: zoptal
  labels:
    app: notification-service
    component: backend
    service: notification
spec:
  ports:
  - port: 4005
    targetPort: 4005
    protocol: TCP
    name: http
  selector:
    app: notification-service
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zoptal-notification-service-hpa
  namespace: zoptal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zoptal-notification-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zoptal-notification-service-pdb
  namespace: zoptal
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: notification-service