apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoptal-project-service
  namespace: zoptal
  labels:
    app: project-service
    component: backend
    service: project
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
        component: backend
        service: project
    spec:
      containers:
      - name: project-service
        image: zoptal/project-service:latest
        ports:
        - containerPort: 4002
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: zoptal-config
              key: NODE_ENV
        - name: PORT
          value: "4002"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: REDIS_URL
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: zoptal-config
              key: AUTH_SERVICE_URL
        - name: AI_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: zoptal-config
              key: AI_SERVICE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: JWT_SECRET
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: zoptal-config
              key: AWS_REGION
        - name: AWS_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: AWS_S3_BUCKET
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: GITHUB_APP_ID
        - name: GITHUB_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: GITHUB_PRIVATE_KEY
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              name: zoptal-secrets
              key: GITLAB_TOKEN
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4002
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 4002
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      initContainers:
      - name: wait-for-auth-service
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          until curl -f http://zoptal-auth-service:4001/health; do
            echo "Waiting for Auth Service..."
            sleep 5
          done

---
apiVersion: v1
kind: Service
metadata:
  name: zoptal-project-service
  namespace: zoptal
  labels:
    app: project-service
    component: backend
    service: project
spec:
  ports:
  - port: 4002
    targetPort: 4002
    protocol: TCP
    name: http
  selector:
    app: project-service
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zoptal-project-service-hpa
  namespace: zoptal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zoptal-project-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zoptal-project-service-pdb
  namespace: zoptal
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: project-service